version: "3"

services: 
  mongo-clean:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
  api:
    container_name: api-container
    build: .
    image: clean-node-api
    restart: always
    volumes: 
      - ./dist:/usr/src/clean-node-api/dist
    command: npm start
    ports:
      - "5050:5050"
    links:
      - mongo
